---
# file: handlers/main.yml
#

- name: restart haproxy_exporter
  service: name=haproxy_exporter state=restarted

- name: reload haproxy_exporter
  service: name=haproxy_exporter state=reloaded

- name: stop haproxy_exporter
  service: name=haproxy_exporter state=stopped
